name: Cachix
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@V27

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v15
      with:
        name: varnam-nix
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build nix flake
      run: nix build -L .#libgovarnam .#fcitx5-varnam
